server:
  port: 10001
# mysql
spring:
  datasource:
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  cloud:
    nacos:
      server-addr: ss:8848
  application:
    name: gulimall-product
  messages:
    encoding: UTF-8
  redis:
    host: localhost
    port: 6379
    password: root
  cache:
    type: redis
  thymeleaf:
    cache: false
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10