spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: ss:8848
  thymeleaf:
    cache: false
  redis:
    password: root
  session:
    store-type: redis
    #test 1 day
    timeout: 86400

server:
  port: 20000