spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      server-addr: ss:8848
      discovery:
        server-addr: ss:8848
  thymeleaf:
    cache: false
  redis:
    password: root
  session:
    store-type: redis
es:
  host: 192.168.3.212
server:
  port: 12002