spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        server-addr: localhost:8848
  thymeleaf:
    cache: false
es:
  host: 192.168.3.212
server:
  port: 12000