server:
  port: 88
spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: product
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**,/ping
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: renren-fast
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
        - id: gulimall_search
          uri: lb://gulimall-search
          predicates:
            - Host=search.gulimall.com
        - id: gulimall_host_route
          uri: lb://gulimall-product
          predicates:
            - Host=gulimall.com
