server:
  port: 40000
spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      server-addr: ss:8848
  redis:
    password: root
  session:
    store-type: redis
#配置线程池
gulimall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10
